export * as s3 from './s3';
export * as datadog from './datadog';
export * as vpc from './vpc';
export * as tags from './tags';
export * as zonepair from './zonepair';
export * as eks from './eks';
export * as certificate from './certificate';
export * as staticwebsite from './staticwebsite';
export * as dns from './dns';
